
package fr.ufrsciencestech.panier.View;

import fr.ufrsciencestech.panier.Model.*;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ViewMenu extends javax.swing.JFrame {

    static List<SimpleFruit> lst_instance = new ArrayList<>();
    static List<String> lst_fruit = new ArrayList<>();
    /**
     * Creates new form ViewMenu
     */
    public ViewMenu() {
        try {
            initComponents();
            String packageName = "fr.ufrsciencestech.panier.Model";
            lst_fruit = findSubClasses(packageName, SimpleFruit.class);
        } catch (Exception ex) { Logger.getLogger(ViewMenu.class.getName()).log(Level.SEVERE, null, ex);}
    }

     public static List<String> findSubClasses(String packageName, Class<?> superClass) throws Exception {
        List<String> classNames = new ArrayList<>();

        String path = packageName.replace('.', '/');
        URL resource = ClassLoader.getSystemClassLoader().getResource(path);
        if (resource == null) {
            throw new IllegalArgumentException("Package introuvable : " + packageName);
        }

        File directory = new File(resource.toURI());
        scanDirectory(directory, packageName, superClass, classNames);

        return classNames;
    }

    private static void scanDirectory(File directory, String packageName, Class<?> superClass, List<String> classNames) throws Exception {
        if (!directory.exists()) return;

        for (File file : directory.listFiles()) {
            if (file.isDirectory()) {
                // Scanner récursivement les sous-packages
                scanDirectory(file, packageName + "." + file.getName(), superClass, classNames);
            } else if (file.getName().endsWith(".class")) {
                String fullClassName = packageName + "." + file.getName().replace(".class", "");
                try {
                    Class<?> clazz = Class.forName(fullClassName);
                    if (superClass.isAssignableFrom(clazz) && !clazz.equals(superClass)) {
                        // Ajouter le nom simple (sans package)
                        classNames.add(clazz.getSimpleName());
                    }
                } catch (NoClassDefFoundError | ClassNotFoundException e) {
                    // Ignorer les classes non chargeables
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Binstance = new javax.swing.JButton();
        Bpanier = new javax.swing.JButton();
        Bcreation = new javax.swing.JButton();
        Bboycott = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Binstance.setText("Instance");
        Binstance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinstanceActionPerformed(evt);
            }
        });

        Bpanier.setText("Panier");
        Bpanier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpanierActionPerformed(evt);
            }
        });

        Bcreation.setText("Création");
        Bcreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcreationActionPerformed(evt);
            }
        });

        Bboycott.setText("Boycott");
        Bboycott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BboycottActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bboycott, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(Bcreation, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(Binstance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bpanier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Binstance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bpanier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bcreation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bboycott, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BinstanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinstanceActionPerformed
        new ViewGlobal().setVisible(true);
    }//GEN-LAST:event_BinstanceActionPerformed

    private void BpanierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpanierActionPerformed
        new ViewBasket().setVisible(true);
    }//GEN-LAST:event_BpanierActionPerformed

    private void BcreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcreationActionPerformed
        new ViewFormulaire().setVisible(true);
    }//GEN-LAST:event_BcreationActionPerformed

    private void BboycottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BboycottActionPerformed
        new ViewBoycott().setVisible(true);
    }//GEN-LAST:event_BboycottActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bboycott;
    private javax.swing.JButton Bcreation;
    private javax.swing.JButton Binstance;
    private javax.swing.JButton Bpanier;
    // End of variables declaration//GEN-END:variables
}
