/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.panier;

import java.beans.PropertyChangeEvent;
import javax.swing.JFrame;

/**
 *
 * @author Ostronix
 */
public class VueGSwing extends JFrame implements VueG {

    /**
     * Creates new form VueGSwing
     */
    public VueGSwing() {
        initComponents();
        PlusCB.setName("PlusCB");
        Moins.setName("Moins");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AjoutFruit = new javax.swing.JPanel();
        PlusCB = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Moins = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 320));

        AjoutFruit.setMaximumSize(new java.awt.Dimension(32842, 50));
        AjoutFruit.setMinimumSize(new java.awt.Dimension(0, 0));
        AjoutFruit.setPreferredSize(new java.awt.Dimension(0, 50));
        AjoutFruit.setLayout(new javax.swing.BoxLayout(AjoutFruit, javax.swing.BoxLayout.LINE_AXIS));

        PlusCB.setLabel("+");
        PlusCB.setMaximumSize(new java.awt.Dimension(1000, 1000));
        PlusCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusCBActionPerformed(evt);
            }
        });
        AjoutFruit.add(PlusCB);

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orange" }));
        AjoutFruit.add(ComboBox);

        getContentPane().add(AjoutFruit, java.awt.BorderLayout.NORTH);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setMinimumSize(new java.awt.Dimension(400, 160));
        jTextArea1.setPreferredSize(new java.awt.Dimension(400, 160));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Moins.setText("-");
        getContentPane().add(Moins, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlusCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlusCBActionPerformed
    
    public void addControleur(Controleur c){
        PlusCB.addActionListener(c);
        Moins.addActionListener(c);
    }

    public void propertyChange(PropertyChangeEvent evt){
        ModelePanier m = (ModelePanier) evt.getSource();
        jTextArea1.setText(m.getPanier().toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueGSwing().setVisible(true);
            }
        });
    }
    
    public Fruit getFruitCB(){
        switch ((String)ComboBox.getSelectedItem()){
                case "Orange":
                        return new Orange();
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AjoutFruit;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton Moins;
    private javax.swing.JButton PlusCB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
