/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.panier;

import fr.ufrsciencestech.panier.Controleur;
import fr.ufrsciencestech.panier.Panier;
import java.awt.*;
import java.beans.PropertyChangeEvent;
import javax.swing.*;

/**
 *
 * @author Ostronix
 */
public class VueGSwing extends JFrame {

    private JButton inc;
    private JButton dec;
    private JLabel nbOrange;
    
    /**
     * Creates new form VueGSwing
     */
    public VueGSwing() {
        super("CompteurOrangeSwing");
        inc = new JButton("+");
        dec = new JButton("-");
        nbOrange = new JLabel("0",JLabel.CENTER);
        add(inc, BorderLayout.NORTH);
        add(dec, BorderLayout.SOUTH);
        add(nbOrange,BorderLayout.CENTER);
        
        inc.setName("Plus");
        dec.setName("Moins");
        nbOrange.setName("Affichage");
        this.pack();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
    }

    
    public void addControleur(Controleur c){
       getInc().addActionListener(c); 
       getDec().addActionListener(c);
    }
    
    public void propertyChange(PropertyChangeEvent evt){
        Panier p = (Panier)evt.getSource();
        getnbOrange().setText(((Integer)p.getNbFruits()).toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the inc
     */
    public JButton getInc() {
        return inc;
    }
    /**
     * @param jb the inc to set
     */
    public void setInc(JButton jb) {
        this.inc = jb;
    }
    /**
     * @return the dec
     */
    public JButton getDec() {
        return dec;
    }
    /**
     * @param jb the dec to set
     */
    public void setDec(JButton jb) {
        this.dec = jb;
    }
    /**
     * @return the nbOrange
     */
    private JLabel getnbOrange() {
        return nbOrange;
    }
    /**
     * @param jl the nbOrange to set
     */
    public void setnbOrange(JLabel jl) {
        this.nbOrange = jl;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
